# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    environment:
      CC_TEST_REPORTER_ID: 1d1a2c1a218ebb477ae29b87b6b9c385107772ce6713b63ce24171b55bd56db3
    working_directory: /go/src/github.com/emman27/jenkinsctl
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: go get -v -t -d ./...
      - run: go test -v -coverprofile=c.out ./...
      - run: ./cc-test-reporter after-build --exit-code $?
